use super::ported;
use crate::case::{CaseDefinition, CaseMetadata};

pub(crate) const DEFINITIONS: &[CaseDefinition] = &[
    CaseDefinition::new(CaseMetadata::new("check.should-validate-config-without-side-effects", "check.check_should_validate_config_without_side_effects", &["#treeboot-check"]), ported::check::check_should_validate_config_without_side_effects),
    CaseDefinition::new(CaseMetadata::new("check.should-support-json-yaml-and-text-formats", "check.check_should_support_json_yaml_and_text_formats", &["#treeboot-check"]), ported::check::check_should_support_json_yaml_and_text_formats),
    CaseDefinition::new(CaseMetadata::new("check.should-fail-when-run-validation-fails", "check.check_should_fail_when_run_validation_fails", &["#treeboot-check"]), ported::check::check_should_fail_when_run_validation_fails),
    CaseDefinition::new(CaseMetadata::new("check.should-fail-when-teardown-validation-fails", "check.check_should_fail_when_teardown_validation_fails", &["#treeboot-check"]), ported::check::check_should_fail_when_teardown_validation_fails),
    CaseDefinition::new(CaseMetadata::new("check.should-report-all-phase-validation-failures-in-order", "check.check_should_report_all_phase_validation_failures_in_order", &["#treeboot-check"]), ported::check::check_should_report_all_phase_validation_failures_in_order),
    CaseDefinition::new(CaseMetadata::new("check.should-fail-for-invalid-ignore-patterns", "check.check_should_fail_for_invalid_ignore_patterns", &["#treeboot-check"]), ported::check::check_should_fail_for_invalid_ignore_patterns),
    CaseDefinition::new(CaseMetadata::new("check.should-fail-for-invalid-default-ignore-patterns", "check.check_should_fail_for_invalid_default_ignore_patterns", &["#treeboot-check"]), ported::check::check_should_fail_for_invalid_default_ignore_patterns),
    CaseDefinition::new(CaseMetadata::new("check.should-succeed-for-missing-config-unless-strict", "check.check_should_succeed_for_missing_config_unless_strict", &["#treeboot-check"]), ported::check::check_should_succeed_for_missing_config_unless_strict),
    CaseDefinition::new(CaseMetadata::new("check.should-skip-root-checkout-unless-strict", "check.check_should_skip_root_checkout_unless_strict", &["#treeboot-check"]), ported::check::check_should_skip_root_checkout_unless_strict),
    CaseDefinition::new(CaseMetadata::new("check.output-shortcuts.conflict-with-format", "check.check_output_shortcuts_should_conflict_with_format", &["#treeboot-check"]), ported::check::check_output_shortcuts_should_conflict_with_format),
    CaseDefinition::new(CaseMetadata::new("check.should-fail-before-side-effects-for-invalid-env-override", "check.check_should_fail_before_side_effects_for_invalid_env_override", &["#treeboot-check"]), ported::check::check_should_fail_before_side_effects_for_invalid_env_override),
    CaseDefinition::new(CaseMetadata::new("check.should-reject-invalid-source-boundary-env-override", "check.check_should_reject_invalid_source_boundary_env_override", &["#treeboot-check"]), ported::check::check_should_reject_invalid_source_boundary_env_override),
    CaseDefinition::new(CaseMetadata::new("check.should-reject-invalid-target-boundary-env-override", "check.check_should_reject_invalid_target_boundary_env_override", &["#treeboot-check"]), ported::check::check_should_reject_invalid_target_boundary_env_override),
    CaseDefinition::new(CaseMetadata::new("check.should-honor-source-boundary-environment-override", "check.check_should_honor_source_boundary_environment_override", &["#treeboot-check"]), ported::check::check_should_honor_source_boundary_environment_override),
    CaseDefinition::new(CaseMetadata::new("check.should-validate-existing-symlink-to-root-source-in-subdirectory", "check.check_should_validate_existing_symlink_to_root_source_in_subdirectory", &["#treeboot-check"]), ported::check::check_should_validate_existing_symlink_to_root_source_in_subdirectory),
    CaseDefinition::new(CaseMetadata::new("check.should-honor-source-boundary-environment-override-for-symlink", "check.check_should_honor_source_boundary_environment_override_for_symlink", &["#treeboot-check"]), ported::check::check_should_honor_source_boundary_environment_override_for_symlink),
    CaseDefinition::new(CaseMetadata::new("check.should-honor-target-boundary-environment-override-for-symlink", "check.check_should_honor_target_boundary_environment_override_for_symlink", &["#treeboot-check"]), ported::check::check_should_honor_target_boundary_environment_override_for_symlink),
    CaseDefinition::new(CaseMetadata::new("check.should-accept-absolute-paths-inside-root-and-worktree", "check.check_should_accept_absolute_paths_inside_root_and_worktree", &["#treeboot-check"]), ported::check::check_should_accept_absolute_paths_inside_root_and_worktree),
    CaseDefinition::new(CaseMetadata::new("check.env-target-override.beat-config-target-override", "check.check_env_target_override_should_beat_config_target_override", &["#treeboot-check"]), ported::check::check_env_target_override_should_beat_config_target_override),
    #[cfg(unix)]
    CaseDefinition::new(CaseMetadata::new("check.should-ignore-executable-legacy-script-and-validate-config", "check.check_should_ignore_executable_legacy_script_and_validate_config", &["#treeboot-check"]), ported::check::check_should_ignore_executable_legacy_script_and_validate_config),
    #[cfg(not(unix))]
    CaseDefinition::skipped(CaseMetadata::new("check.should-ignore-executable-legacy-script-and-validate-config", "check.check_should_ignore_executable_legacy_script_and_validate_config", &["#treeboot-check"]), "requires a Unix host"),
    #[cfg(unix)]
    CaseDefinition::new(CaseMetadata::new("check.config-option.ignore-legacy-script-and-validate-requested-config", "check.check_config_option_should_ignore_legacy_script_and_validate_requested_config", &["#treeboot-check"]), ported::check::check_config_option_should_ignore_legacy_script_and_validate_requested_config),
    #[cfg(not(unix))]
    CaseDefinition::skipped(CaseMetadata::new("check.config-option.ignore-legacy-script-and-validate-requested-config", "check.check_config_option_should_ignore_legacy_script_and_validate_requested_config", &["#treeboot-check"]), "requires a Unix host"),
    CaseDefinition::new(CaseMetadata::new("check.no-init-script-flag.be-usage-error", "check.check_no_init_script_flag_should_be_usage_error", &["#treeboot-check"]), ported::check::check_no_init_script_flag_should_be_usage_error),
    CaseDefinition::new(CaseMetadata::new("check.should-warn-on-zero-match-include-and-stay-ok", "check.check_should_warn_on_zero_match_include_and_stay_ok", &["#treeboot-check"]), ported::check::check_should_warn_on_zero_match_include_and_stay_ok),
    CaseDefinition::new(CaseMetadata::new("check.json.carry-zero-match-include-warnings", "check.check_json_should_carry_zero_match_include_warnings", &["#treeboot-check"]), ported::check::check_json_should_carry_zero_match_include_warnings),
    CaseDefinition::new(CaseMetadata::new("check.should-reject-include-with-sync-delete", "check.check_should_reject_include_with_sync_delete", &["#treeboot-check"]), ported::check::check_should_reject_include_with_sync_delete),
    CaseDefinition::new(CaseMetadata::new("check.yaml.carry-zero-match-include-warnings", "check.check_yaml_should_carry_zero_match_include_warnings", &["#treeboot-check"]), ported::check::check_yaml_should_carry_zero_match_include_warnings),
    CaseDefinition::new(CaseMetadata::new("cli.help.print-usage", "cli.help_should_print_usage", &["#cli-surface-subcommands-and-one-default-path"]), ported::cli::help_should_print_usage),
    CaseDefinition::new(CaseMetadata::new("cli.plan-help.print-usage", "cli.plan_help_should_print_usage", &["#treeboot-plan"]), ported::cli::plan_help_should_print_usage),
    CaseDefinition::new(CaseMetadata::new("cli.version-flags.print-package-and-spec-version", "cli.version_flags_should_print_package_and_spec_version", &["#cli-surface-subcommands-and-one-default-path"]), ported::cli::version_flags_should_print_package_and_spec_version),
    CaseDefinition::new(CaseMetadata::new("cli.unknown-option.exit-with-usage-error", "cli.unknown_option_should_exit_with_usage_error", &["#cli-surface-subcommands-and-one-default-path"]), ported::cli::unknown_option_should_exit_with_usage_error),
    CaseDefinition::new(CaseMetadata::new("cli.legacy-no-commands-option.exit-with-usage-error", "cli.legacy_no_commands_option_should_exit_with_usage_error", &["#cli-surface-subcommands-and-one-default-path"]), ported::cli::legacy_no_commands_option_should_exit_with_usage_error),
    CaseDefinition::new(CaseMetadata::new("cli.unsupported-structured-output-options.exit-with-usage-error", "cli.unsupported_structured_output_options_should_be_usage_errors", &["#cli-surface-subcommands-and-one-default-path"]), ported::cli::unsupported_structured_output_options_should_be_usage_errors),
    CaseDefinition::new(CaseMetadata::new("completions.supported-shells.emit-scripts", "completions.completions_supported_shells_should_emit_scripts", &["#treeboot-completions"]), ported::completions::completions_supported_shells_should_emit_scripts),
    CaseDefinition::new(CaseMetadata::new("completions.unsupported-shell.exit-with-usage-error", "completions.completions_unsupported_shell_should_exit_with_usage_error", &["#treeboot-completions"]), ported::completions::completions_unsupported_shell_should_exit_with_usage_error),
    CaseDefinition::new(CaseMetadata::new("completions.should-not-require-git-or-config-discovery", "completions.completions_should_not_require_git_or_config_discovery", &["#treeboot-completions"]), ported::completions::completions_should_not_require_git_or_config_discovery),
    CaseDefinition::new(CaseMetadata::new("completions.expose-plan-and-structured-output-flags", "completions.completions_should_expose_plan_and_structured_output_flags", &["#treeboot-completions"]), ported::completions::completions_should_expose_plan_and_structured_output_flags),
    CaseDefinition::new(CaseMetadata::new("config.command.print-normalized-config", "config.config_command_should_print_normalized_config", &["#treeboot-config"]), ported::config::config_command_should_print_normalized_config),
    CaseDefinition::new(CaseMetadata::new("config.command.show-effective-identity-in-root-checkout", "config.config_command_should_show_effective_identity_in_root_checkout", &["#treeboot-config"]), ported::config::config_command_should_show_effective_identity_in_root_checkout),
    CaseDefinition::new(CaseMetadata::new("config.command.reject-incompatible-identity-lengths", "config.config_command_should_reject_incompatible_identity_lengths", &["#treeboot-config"]), ported::config::config_command_should_reject_incompatible_identity_lengths),
    CaseDefinition::new(CaseMetadata::new("config.command.print-teardown-commands", "config.config_command_should_print_teardown_commands", &["#treeboot-config"]), ported::config::config_command_should_print_teardown_commands),
    CaseDefinition::new(CaseMetadata::new("config.command-json.print-normalized-config", "config.config_command_json_should_print_normalized_config", &["#treeboot-config"]), ported::config::config_command_json_should_print_normalized_config),
    CaseDefinition::new(CaseMetadata::new("config.command-json-shortcut.print-normalized-config", "config.config_command_json_shortcut_should_print_normalized_config", &["#treeboot-config"]), ported::config::config_command_json_shortcut_should_print_normalized_config),
    CaseDefinition::new(CaseMetadata::new("config.command-yaml.print-normalized-config", "config.config_command_yaml_should_print_normalized_config", &["#treeboot-config"]), ported::config::config_command_yaml_should_print_normalized_config),
    CaseDefinition::new(CaseMetadata::new("config.command-yaml-shortcut.print-normalized-config", "config.config_command_yaml_shortcut_should_print_normalized_config", &["#treeboot-config"]), ported::config::config_command_yaml_shortcut_should_print_normalized_config),
    CaseDefinition::new(CaseMetadata::new("config.command-text-format.print-normalized-config", "config.config_command_text_format_should_print_normalized_config", &["#treeboot-config"]), ported::config::config_command_text_format_should_print_normalized_config),
    CaseDefinition::new(CaseMetadata::new("config.command-output-shortcuts.conflict-with-each-other", "config.config_command_output_shortcuts_should_conflict_with_each_other", &["#treeboot-config"]), ported::config::config_command_output_shortcuts_should_conflict_with_each_other),
    CaseDefinition::new(CaseMetadata::new("config.command-json.conflict-with-format", "config.config_command_json_should_conflict_with_format", &["#treeboot-config"]), ported::config::config_command_json_should_conflict_with_format),
    CaseDefinition::new(CaseMetadata::new("config.command-yaml.conflict-with-format", "config.config_command_yaml_should_conflict_with_format", &["#treeboot-config"]), ported::config::config_command_yaml_should_conflict_with_format),
    CaseDefinition::new(CaseMetadata::new("config.command-missing-config.exit-with-runtime-failure", "config.config_command_missing_config_should_exit_with_runtime_failure", &["#treeboot-config"]), ported::config::config_command_missing_config_should_exit_with_runtime_failure),
    CaseDefinition::new(CaseMetadata::new("config.command-config-option.use-requested-file", "config.config_command_config_option_should_use_requested_file", &["#treeboot-config"]), ported::config::config_command_config_option_should_use_requested_file),
    CaseDefinition::new(CaseMetadata::new("config.command.print-file-and-command-options", "config.config_command_should_print_file_and_command_options", &["#treeboot-config"]), ported::config::config_command_should_print_file_and_command_options),
    CaseDefinition::new(CaseMetadata::new("config.command.reject-async-command-field", "config.config_command_should_reject_async_command_field", &["#treeboot-config"]), ported::config::config_command_should_reject_async_command_field),
    CaseDefinition::new(CaseMetadata::new("config.command.reject-args-with-shell-run", "config.config_command_should_reject_args_with_shell_run", &["#treeboot-config"]), ported::config::config_command_should_reject_args_with_shell_run),
    CaseDefinition::new(CaseMetadata::new("config.command.reject-missing-operation-in-mixed-file-entry", "config.config_command_should_reject_missing_operation_in_mixed_file_entry", &["#treeboot-config"]), ported::config::config_command_should_reject_missing_operation_in_mixed_file_entry),
    CaseDefinition::new(CaseMetadata::new("config.command-root-option.resolve-json-source-paths", "config.config_command_root_option_should_resolve_json_source_paths", &["#treeboot-config"]), ported::config::config_command_root_option_should_resolve_json_source_paths),
    CaseDefinition::new(CaseMetadata::new("config.command-invalid-config.exit-with-config-error", "config.config_command_invalid_config_should_exit_with_config_error", &["#treeboot-config"]), ported::config::config_command_invalid_config_should_exit_with_config_error),
    CaseDefinition::new(CaseMetadata::new("config.command.reject-ignore-metadata-on-symlink", "config.config_command_should_reject_ignore_metadata_on_symlink", &["#treeboot-config"]), ported::config::config_command_should_reject_ignore_metadata_on_symlink),
    CaseDefinition::new(CaseMetadata::new("config.command.warn-when-run-validation-would-fail", "config.config_command_should_warn_when_run_validation_would_fail", &["#treeboot-config"]), ported::config::config_command_should_warn_when_run_validation_would_fail),
    CaseDefinition::new(CaseMetadata::new("config.command.warn-when-teardown-validation-would-fail", "config.config_command_should_warn_when_teardown_validation_would_fail", &["#treeboot-config"]), ported::config::config_command_should_warn_when_teardown_validation_would_fail),
    CaseDefinition::new(CaseMetadata::new("config.command-json.warn-when-run-validation-would-fail", "config.config_command_json_should_warn_when_run_validation_would_fail", &["#treeboot-config"]), ported::config::config_command_json_should_warn_when_run_validation_would_fail),
    CaseDefinition::new(CaseMetadata::new("config.command.warn-when-config-strict-would-fail", "config.config_command_should_warn_when_config_strict_would_fail", &["#treeboot-config"]), ported::config::config_command_should_warn_when_config_strict_would_fail),
    CaseDefinition::new(CaseMetadata::new("config.command.warn-when-env-strict-would-fail", "config.config_command_should_warn_when_env_strict_would_fail", &["#treeboot-config"]), ported::config::config_command_should_warn_when_env_strict_would_fail),
    CaseDefinition::new(CaseMetadata::new("config.command.print-include-and-warn-on-zero-match", "config.config_command_should_print_include_and_warn_on_zero_match", &["#treeboot-config"]), ported::config::config_command_should_print_include_and_warn_on_zero_match),
    CaseDefinition::new(CaseMetadata::new("config.command-json.stay-parseable-with-include-warnings", "config.config_command_json_should_stay_parseable_with_include_warnings", &["#treeboot-config"]), ported::config::config_command_json_should_stay_parseable_with_include_warnings),
    CaseDefinition::new(CaseMetadata::new("doctor.should-report-diagnostics-as-text-json-and-yaml", "doctor.doctor_should_report_diagnostics_as_text_json_and_yaml", &["#treeboot-doctor"]), ported::doctor::doctor_should_report_diagnostics_as_text_json_and_yaml),
    CaseDefinition::new(CaseMetadata::new("doctor.strict.treat-missing-config-as-fatal", "doctor.doctor_strict_should_treat_missing_config_as_fatal", &["#treeboot-doctor"]), ported::doctor::doctor_strict_should_treat_missing_config_as_fatal),
    CaseDefinition::new(CaseMetadata::new("doctor.should-apply-environment-strict-to-missing-config", "doctor.doctor_should_apply_environment_strict_to_missing_config", &["#treeboot-doctor"]), ported::doctor::doctor_should_apply_environment_strict_to_missing_config),
    CaseDefinition::new(CaseMetadata::new("doctor.strict.report-root-checkout-as-fatal-diagnostic", "doctor.doctor_strict_should_report_root_checkout_as_fatal_diagnostic", &["#treeboot-doctor"]), ported::doctor::doctor_strict_should_report_root_checkout_as_fatal_diagnostic),
    CaseDefinition::new(CaseMetadata::new("doctor.should-apply-environment-strict-to-root-checkout", "doctor.doctor_should_apply_environment_strict_to_root_checkout", &["#treeboot-doctor"]), ported::doctor::doctor_should_apply_environment_strict_to_root_checkout),
    CaseDefinition::new(CaseMetadata::new("doctor.strict.validate-config-with-strict-policy", "doctor.doctor_strict_should_validate_config_with_strict_policy", &["#treeboot-doctor"]), ported::doctor::doctor_strict_should_validate_config_with_strict_policy),
    CaseDefinition::new(CaseMetadata::new("doctor.strict.report-missing-requested-config", "doctor.doctor_strict_should_report_missing_requested_config", &["#treeboot-doctor"]), ported::doctor::doctor_strict_should_report_missing_requested_config),
    CaseDefinition::new(CaseMetadata::new("doctor.should-apply-environment-strict-to-config-validation", "doctor.doctor_should_apply_environment_strict_to_config_validation", &["#treeboot-doctor"]), ported::doctor::doctor_should_apply_environment_strict_to_config_validation),
    CaseDefinition::new(CaseMetadata::new("doctor.should-report-teardown-validation-errors-separately", "doctor.doctor_should_report_teardown_validation_errors_separately", &["#treeboot-doctor"]), ported::doctor::doctor_should_report_teardown_validation_errors_separately),
    CaseDefinition::new(CaseMetadata::new("doctor.should-support-text-format-and-yaml-shortcut", "doctor.doctor_should_support_text_format_and_yaml_shortcut", &["#treeboot-doctor"]), ported::doctor::doctor_should_support_text_format_and_yaml_shortcut),
    CaseDefinition::new(CaseMetadata::new("doctor.should-warn-when-default-branch-is-unknown", "doctor.doctor_should_warn_when_default_branch_is_unknown", &["#treeboot-doctor"]), ported::doctor::doctor_should_warn_when_default_branch_is_unknown),
    CaseDefinition::new(CaseMetadata::new("doctor.should-exit-nonzero-for-invalid-config-after-printing-report", "doctor.doctor_should_exit_nonzero_for_invalid_config_after_printing_report", &["#treeboot-doctor"]), ported::doctor::doctor_should_exit_nonzero_for_invalid_config_after_printing_report),
    CaseDefinition::new(CaseMetadata::new("doctor.text.report-fatal-config-diagnostics", "doctor.doctor_text_should_report_fatal_config_diagnostics", &["#treeboot-doctor"]), ported::doctor::doctor_text_should_report_fatal_config_diagnostics),
    CaseDefinition::new(CaseMetadata::new("doctor.should-report-invalid-env-override-as-fatal", "doctor.doctor_should_report_invalid_env_override_as_fatal", &["#treeboot-doctor"]), ported::doctor::doctor_should_report_invalid_env_override_as_fatal),
    CaseDefinition::new(CaseMetadata::new("doctor.output-shortcuts.conflict-with-format", "doctor.doctor_output_shortcuts_should_conflict_with_format", &["#treeboot-doctor"]), ported::doctor::doctor_output_shortcuts_should_conflict_with_format),
    CaseDefinition::new(CaseMetadata::new("doctor.should-fail-outside-git-worktree", "doctor.doctor_should_fail_outside_git_worktree", &["#treeboot-doctor"]), ported::doctor::doctor_should_fail_outside_git_worktree),
    #[cfg(unix)]
    CaseDefinition::new(CaseMetadata::new("doctor.should-ignore-legacy-script-and-omit-script-diagnostic", "doctor.doctor_should_ignore_legacy_script_and_omit_script_diagnostic", &["#treeboot-doctor"]), ported::doctor::doctor_should_ignore_legacy_script_and_omit_script_diagnostic),
    #[cfg(not(unix))]
    CaseDefinition::skipped(CaseMetadata::new("doctor.should-ignore-legacy-script-and-omit-script-diagnostic", "doctor.doctor_should_ignore_legacy_script_and_omit_script_diagnostic", &["#treeboot-doctor"]), "requires a Unix host"),
    #[cfg(unix)]
    CaseDefinition::new(CaseMetadata::new("doctor.strict.fail-for-legacy-script-only-repo", "doctor.doctor_strict_should_fail_for_legacy_script_only_repo", &["#treeboot-doctor"]), ported::doctor::doctor_strict_should_fail_for_legacy_script_only_repo),
    #[cfg(not(unix))]
    CaseDefinition::skipped(CaseMetadata::new("doctor.strict.fail-for-legacy-script-only-repo", "doctor.doctor_strict_should_fail_for_legacy_script_only_repo", &["#treeboot-doctor"]), "requires a Unix host"),
    CaseDefinition::new(CaseMetadata::new("doctor.no-init-script-flag.be-usage-error", "doctor.doctor_no_init_script_flag_should_be_usage_error", &["#treeboot-doctor"]), ported::doctor::doctor_no_init_script_flag_should_be_usage_error),
    #[cfg(unix)]
    CaseDefinition::new(CaseMetadata::new("doctor.config-option.ignore-legacy-script-and-validate-requested-config", "doctor.doctor_config_option_should_ignore_legacy_script_and_validate_requested_config", &["#treeboot-doctor"]), ported::doctor::doctor_config_option_should_ignore_legacy_script_and_validate_requested_config),
    #[cfg(not(unix))]
    CaseDefinition::skipped(CaseMetadata::new("doctor.config-option.ignore-legacy-script-and-validate-requested-config", "doctor.doctor_config_option_should_ignore_legacy_script_and_validate_requested_config", &["#treeboot-doctor"]), "requires a Unix host"),
    CaseDefinition::new(CaseMetadata::new("env.should-print-child-environment-as-text-json-and-yaml", "env.env_should_print_child_environment_as_text_json_and_yaml", &["#treeboot-env"]), ported::env::env_should_print_child_environment_as_text_json_and_yaml),
    CaseDefinition::new(CaseMetadata::new("env.should-use-discovered-worktree-identifier-config", "env.env_should_use_discovered_worktree_identifier_config", &["#treeboot-env"]), ported::env::env_should_use_discovered_worktree_identifier_config),
    CaseDefinition::new(CaseMetadata::new("env.config-option.select-requested-identifier-config", "env.env_config_option_should_select_requested_identifier_config", &["#treeboot-env"]), ported::env::env_config_option_should_select_requested_identifier_config),
    CaseDefinition::new(CaseMetadata::new("env.should-fail-for-invalid-discovered-config", "env.env_should_fail_for_invalid_discovered_config", &["#treeboot-env"]), ported::env::env_should_fail_for_invalid_discovered_config),
    CaseDefinition::new(CaseMetadata::new("env.should-fail-for-missing-explicit-config", "env.env_should_fail_for_missing_explicit_config", &["#treeboot-env"]), ported::env::env_should_fail_for_missing_explicit_config),
    CaseDefinition::new(CaseMetadata::new("env.should-resolve-configured-identifier-in-root-checkout", "env.env_should_resolve_configured_identifier_in_root_checkout", &["#treeboot-env"]), ported::env::env_should_resolve_configured_identifier_in_root_checkout),
    CaseDefinition::new(CaseMetadata::new("env.paths.not-use-windows-verbatim-prefix", "env.env_paths_should_not_use_windows_verbatim_prefix", &["#treeboot-env"]), ported::env::env_paths_should_not_use_windows_verbatim_prefix),
    CaseDefinition::new(CaseMetadata::new("env.should-support-text-format-and-yaml-shortcut", "env.env_should_support_text_format_and_yaml_shortcut", &["#treeboot-env"]), ported::env::env_should_support_text_format_and_yaml_shortcut),
    CaseDefinition::new(CaseMetadata::new("env.root-option.override-source-checkout", "env.env_root_option_should_override_source_checkout", &["#treeboot-env"]), ported::env::env_root_option_should_override_source_checkout),
    CaseDefinition::new(CaseMetadata::new("env.root-override.not-change-worktree-identifier", "env.env_root_override_should_not_change_worktree_identifier", &["#treeboot-env"]), ported::env::env_root_override_should_not_change_worktree_identifier),
    CaseDefinition::new(CaseMetadata::new("env.root-aliases.not-change-worktree-identifier", "env.env_root_aliases_should_not_change_worktree_identifier", &["#treeboot-env"]), ported::env::env_root_aliases_should_not_change_worktree_identifier),
    CaseDefinition::new(CaseMetadata::new("env.branch-creation-checkout-rename-and-detach.not-change-identifier", "env.env_branch_creation_checkout_rename_and_detach_should_not_change_identifier", &["#treeboot-env"]), ported::env::env_branch_creation_checkout_rename_and_detach_should_not_change_identifier),
    #[cfg(unix)]
    CaseDefinition::new(CaseMetadata::new("env.symlink-alias.not-change-worktree-identifier", "env.env_symlink_alias_should_not_change_worktree_identifier", &["#treeboot-env"]), ported::env::env_symlink_alias_should_not_change_worktree_identifier),
    #[cfg(not(unix))]
    CaseDefinition::skipped(CaseMetadata::new("env.symlink-alias.not-change-worktree-identifier", "env.env_symlink_alias_should_not_change_worktree_identifier", &["#treeboot-env"]), "requires a Unix host"),
    CaseDefinition::new(CaseMetadata::new("env.root-environment-alias.override-source-checkout", "env.env_root_environment_alias_should_override_source_checkout", &["#treeboot-env"]), ported::env::env_root_environment_alias_should_override_source_checkout),
    CaseDefinition::new(CaseMetadata::new("env.root-environment-alias.resolve-relative-to-cwd", "env.env_root_environment_alias_should_resolve_relative_to_cwd", &["#treeboot-env"]), ported::env::env_root_environment_alias_should_resolve_relative_to_cwd),
    CaseDefinition::new(CaseMetadata::new("env.should-fail-when-root-override-does-not-exist", "env.env_should_fail_when_root_override_does_not_exist", &["#treeboot-env"]), ported::env::env_should_fail_when_root_override_does_not_exist),
    CaseDefinition::new(CaseMetadata::new("env.output-shortcuts.conflict-with-format", "env.env_output_shortcuts_should_conflict_with_format", &["#treeboot-env"]), ported::env::env_output_shortcuts_should_conflict_with_format),
    CaseDefinition::new(CaseMetadata::new("env.should-fail-outside-git-worktree", "env.env_should_fail_outside_git_worktree", &["#treeboot-env"]), ported::env::env_should_fail_outside_git_worktree),
    CaseDefinition::new(CaseMetadata::new("init.config.create-starter-config", "init.init_config_should_create_starter_config", &["#treeboot-init"]), ported::init::init_config_should_create_starter_config),
    CaseDefinition::new(CaseMetadata::new("init.without-kind.create-starter-config", "init.init_without_kind_should_create_starter_config", &["#treeboot-init"]), ported::init::init_without_kind_should_create_starter_config),
    CaseDefinition::new(CaseMetadata::new("init.config.fail-when-target-exists", "init.init_config_should_fail_when_target_exists", &["#treeboot-init"]), ported::init::init_config_should_fail_when_target_exists),
    CaseDefinition::new(CaseMetadata::new("init.force.be-usage-error", "init.init_force_should_be_usage_error", &["#treeboot-init"]), ported::init::init_force_should_be_usage_error),
    CaseDefinition::new(CaseMetadata::new("init.config.fail-when-target-is-symlink-without-writing-through-it", "init.init_config_should_fail_when_target_is_symlink_without_writing_through_it", &["#treeboot-init"]), ported::init::init_config_should_fail_when_target_is_symlink_without_writing_through_it),
    CaseDefinition::new(CaseMetadata::new("init.path.create-parent-directories", "init.init_path_should_create_parent_directories", &["#treeboot-init"]), ported::init::init_path_should_create_parent_directories),
    CaseDefinition::new(CaseMetadata::new("init.path.fail-when-parent-component-is-file", "init.init_path_should_fail_when_parent_component_is_file", &["#treeboot-init"]), ported::init::init_path_should_fail_when_parent_component_is_file),
    CaseDefinition::new(CaseMetadata::new("init.script-long-flag.be-usage-error", "init.init_script_long_flag_should_be_usage_error", &["#treeboot-init"]), ported::init::init_script_long_flag_should_be_usage_error),
    CaseDefinition::new(CaseMetadata::new("init.script-short-flag.be-usage-error", "init.init_script_short_flag_should_be_usage_error", &["#treeboot-init"]), ported::init::init_script_short_flag_should_be_usage_error),
    CaseDefinition::new(CaseMetadata::new("manual.commands.require-sources", "manual.manual_commands_should_require_sources", &["#manual-file-operation-commands"]), ported::manual::manual_commands_should_require_sources),
    CaseDefinition::new(CaseMetadata::new("manual.copy.create-files-and-directories-from-root", "manual.copy_should_create_files_and_directories_from_root", &["#manual-file-operation-commands"]), ported::manual::copy_should_create_files_and_directories_from_root),
    CaseDefinition::new(CaseMetadata::new("manual.copy.accept-absolute-source-and-target-inside-context", "manual.copy_should_accept_absolute_source_and_target_inside_context", &["#manual-file-operation-commands"]), ported::manual::copy_should_accept_absolute_source_and_target_inside_context),
    CaseDefinition::new(CaseMetadata::new("manual.copy.apply-explicit-ignore-without-loading-gitignore", "manual.copy_should_apply_explicit_ignore_without_loading_gitignore", &["#manual-file-operation-commands"]), ported::manual::copy_should_apply_explicit_ignore_without_loading_gitignore),
    CaseDefinition::new(CaseMetadata::new("manual.copy.apply-config-default-ignore", "manual.copy_should_apply_config_default_ignore", &["#manual-file-operation-commands"]), ported::manual::copy_should_apply_config_default_ignore),
    CaseDefinition::new(CaseMetadata::new("manual.copy.allow-cli-ignore-to-reinclude-config-default-ignore", "manual.copy_should_allow_cli_ignore_to_reinclude_config_default_ignore", &["#manual-file-operation-commands"]), ported::manual::copy_should_allow_cli_ignore_to_reinclude_config_default_ignore),
    CaseDefinition::new(CaseMetadata::new("manual.copy.place-multiple-sources-under-target-prefix", "manual.copy_should_place_multiple_sources_under_target_prefix", &["#manual-file-operation-commands"]), ported::manual::copy_should_place_multiple_sources_under_target_prefix),
    CaseDefinition::new(CaseMetadata::new("manual.symlink.create-relative-link", "manual.symlink_should_create_relative_link", &["#manual-file-operation-commands"]), ported::manual::symlink_should_create_relative_link),
    CaseDefinition::new(CaseMetadata::new("manual.sync.update-changed-files", "manual.sync_should_update_changed_files", &["#manual-file-operation-commands"]), ported::manual::sync_should_update_changed_files),
    #[cfg(unix)]
    CaseDefinition::new(CaseMetadata::new("manual.sync.honor-ignore-metadata-permissions", "manual.sync_should_honor_ignore_metadata_permissions", &["#manual-file-operation-commands"]), ported::manual::sync_should_honor_ignore_metadata_permissions),
    #[cfg(not(unix))]
    CaseDefinition::skipped(CaseMetadata::new("manual.sync.honor-ignore-metadata-permissions", "manual.sync_should_honor_ignore_metadata_permissions", &["#manual-file-operation-commands"]), "requires a Unix host"),
    CaseDefinition::new(CaseMetadata::new("manual.sync-verbose.report-concrete-file-actions", "manual.sync_verbose_should_report_concrete_file_actions", &["#manual-file-operation-commands"]), ported::manual::sync_verbose_should_report_concrete_file_actions),
    CaseDefinition::new(CaseMetadata::new("manual.sync-delete.remove-target-only-files", "manual.sync_delete_should_remove_target_only_files", &["#manual-file-operation-commands"]), ported::manual::sync_delete_should_remove_target_only_files),
    CaseDefinition::new(CaseMetadata::new("manual.sync-delete.preserve-ignored-target-only-files", "manual.sync_delete_should_preserve_ignored_target_only_files", &["#manual-file-operation-commands"]), ported::manual::sync_delete_should_preserve_ignored_target_only_files),
    CaseDefinition::new(CaseMetadata::new("manual.sync-delete.preserve-config-default-ignored-target-only-files", "manual.sync_delete_should_preserve_config_default_ignored_target_only_files", &["#manual-file-operation-commands"]), ported::manual::sync_delete_should_preserve_config_default_ignored_target_only_files),
    CaseDefinition::new(CaseMetadata::new("manual.sync-delete.allow-cli-ignore-to-reinclude-config-default-ignore", "manual.sync_delete_should_allow_cli_ignore_to_reinclude_config_default_ignore", &["#manual-file-operation-commands"]), ported::manual::sync_delete_should_allow_cli_ignore_to_reinclude_config_default_ignore),
    CaseDefinition::new(CaseMetadata::new("manual.sync-no-delete.preserve-target-only-files", "manual.sync_no_delete_should_preserve_target_only_files", &["#manual-file-operation-commands"]), ported::manual::sync_no_delete_should_preserve_target_only_files),
    CaseDefinition::new(CaseMetadata::new("manual.dry-run.report-without-mutation", "manual.dry_run_should_report_without_mutation", &["#manual-file-operation-commands"]), ported::manual::dry_run_should_report_without_mutation),
    CaseDefinition::new(CaseMetadata::new("manual.force.replace-supported-targets", "manual.force_should_replace_supported_targets", &["#manual-file-operation-commands"]), ported::manual::force_should_replace_supported_targets),
    CaseDefinition::new(CaseMetadata::new("manual.root-checkout.skip-manual-file-operations", "manual.root_checkout_should_skip_manual_file_operations", &["#manual-file-operation-commands"]), ported::manual::root_checkout_should_skip_manual_file_operations),
    CaseDefinition::new(CaseMetadata::new("manual.root-checkout.skip-manual-config-parsing", "manual.root_checkout_should_skip_manual_config_parsing", &["#manual-file-operation-commands"]), ported::manual::root_checkout_should_skip_manual_config_parsing),
    CaseDefinition::new(CaseMetadata::new("manual.strict-root-checkout.fail-manual-file-operations", "manual.strict_root_checkout_should_fail_manual_file_operations", &["#manual-file-operation-commands"]), ported::manual::strict_root_checkout_should_fail_manual_file_operations),
    CaseDefinition::new(CaseMetadata::new("manual.invalid-operation-specific-flags.be-usage-errors", "manual.invalid_operation_specific_flags_should_be_usage_errors", &["#manual-file-operation-commands"]), ported::manual::invalid_operation_specific_flags_should_be_usage_errors),
    CaseDefinition::new(CaseMetadata::new("manual.required-missing-source.fail-without-config-locations", "manual.required_missing_source_should_fail_without_config_locations", &["#manual-file-operation-commands"]), ported::manual::required_missing_source_should_fail_without_config_locations),
    CaseDefinition::new(CaseMetadata::new("manual.duplicate-manual-targets.fail-before-side-effects", "manual.duplicate_manual_targets_should_fail_before_side_effects", &["#manual-file-operation-commands"]), ported::manual::duplicate_manual_targets_should_fail_before_side_effects),
    CaseDefinition::new(CaseMetadata::new("manual.overlapping-manual-sync-delete-targets.fail-before-side-effects", "manual.overlapping_manual_sync_delete_targets_should_fail_before_side_effects", &["#manual-file-operation-commands"]), ported::manual::overlapping_manual_sync_delete_targets_should_fail_before_side_effects),
    CaseDefinition::new(CaseMetadata::new("manual.unsafe-source-symlink.fail-before-side-effects", "manual.unsafe_source_symlink_should_fail_before_side_effects", &["#manual-file-operation-commands"]), ported::manual::unsafe_source_symlink_should_fail_before_side_effects),
    CaseDefinition::new(CaseMetadata::new("manual.commands.fail-on-invalid-config-before-side-effects", "manual.manual_commands_should_fail_on_invalid_config_before_side_effects", &["#manual-file-operation-commands"]), ported::manual::manual_commands_should_fail_on_invalid_config_before_side_effects),
    CaseDefinition::new(CaseMetadata::new("manual.commands.use-config-runtime-policy", "manual.manual_commands_should_use_config_runtime_policy", &["#manual-file-operation-commands"]), ported::manual::manual_commands_should_use_config_runtime_policy),
    CaseDefinition::new(CaseMetadata::new("manual.commands.reject-targets-outside-worktree-by-default", "manual.manual_commands_should_reject_targets_outside_worktree_by_default", &["#manual-file-operation-commands"]), ported::manual::manual_commands_should_reject_targets_outside_worktree_by_default),
    CaseDefinition::new(CaseMetadata::new("manual.commands.allow-configured-targets-outside-worktree", "manual.manual_commands_should_allow_configured_targets_outside_worktree", &["#manual-file-operation-commands"]), ported::manual::manual_commands_should_allow_configured_targets_outside_worktree),
    CaseDefinition::new(CaseMetadata::new("manual.config-strict.reject-sync-before-side-effects", "manual.manual_config_strict_should_reject_sync_before_side_effects", &["#manual-file-operation-commands"]), ported::manual::manual_config_strict_should_reject_sync_before_side_effects),
    CaseDefinition::new(CaseMetadata::new("manual.env-false.override-config-strict", "manual.manual_env_false_should_override_config_strict", &["#manual-file-operation-commands"]), ported::manual::manual_env_false_should_override_config_strict),
    CaseDefinition::new(CaseMetadata::new("manual.cli-strict.override-env-and-config-false", "manual.manual_cli_strict_should_override_env_and_config_false", &["#manual-file-operation-commands"]), ported::manual::manual_cli_strict_should_override_env_and_config_false),
    #[cfg(unix)]
    CaseDefinition::new(CaseMetadata::new("manual.commands.ignore-executable-legacy-script", "manual.manual_commands_should_ignore_executable_legacy_script", &["#manual-file-operation-commands"]), ported::manual::manual_commands_should_ignore_executable_legacy_script),
    #[cfg(not(unix))]
    CaseDefinition::skipped(CaseMetadata::new("manual.commands.ignore-executable-legacy-script", "manual.manual_commands_should_ignore_executable_legacy_script", &["#manual-file-operation-commands"]), "requires a Unix host"),
    CaseDefinition::new(CaseMetadata::new("manual.copy.apply-include-patterns", "manual.copy_should_apply_include_patterns", &["#manual-file-operation-commands"]), ported::manual::copy_should_apply_include_patterns),
    CaseDefinition::new(CaseMetadata::new("manual.copy.combine-repeated-include-flags-with-ignore", "manual.copy_should_combine_repeated_include_flags_with_ignore", &["#manual-file-operation-commands"]), ported::manual::copy_should_combine_repeated_include_flags_with_ignore),
    CaseDefinition::new(CaseMetadata::new("manual.include.never-filter-top-level-sources", "manual.include_should_never_filter_top_level_sources", &["#manual-file-operation-commands"]), ported::manual::include_should_never_filter_top_level_sources),
    CaseDefinition::new(CaseMetadata::new("manual.sync-include.conflict-with-delete-flags", "manual.sync_include_should_conflict_with_delete_flags", &["#manual-file-operation-commands"]), ported::manual::sync_include_should_conflict_with_delete_flags),
    CaseDefinition::new(CaseMetadata::new("manual.sync-include.allow-no-delete", "manual.sync_include_should_allow_no_delete", &["#manual-file-operation-commands"]), ported::manual::sync_include_should_allow_no_delete),
    CaseDefinition::new(CaseMetadata::new("manual.copy.reject-inert-include-patterns", "manual.copy_should_reject_inert_include_patterns", &["#manual-file-operation-commands"]), ported::manual::copy_should_reject_inert_include_patterns),
    CaseDefinition::new(CaseMetadata::new("manual.copy.accept-escaped-include-prefixes", "manual.copy_should_accept_escaped_include_prefixes", &["#manual-file-operation-commands"]), ported::manual::copy_should_accept_escaped_include_prefixes),
    CaseDefinition::new(CaseMetadata::new("run.no-args.report-root-checkout-noop", "run.no_args_should_report_root_checkout_noop", &["#treeboot-run"]), ported::run::no_args_should_report_root_checkout_noop),
    CaseDefinition::new(CaseMetadata::new("run.should-report-root-checkout-noop-like-no-args", "run.run_should_report_root_checkout_noop_like_no_args", &["#treeboot-run"]), ported::run::run_should_report_root_checkout_noop_like_no_args),
    CaseDefinition::new(CaseMetadata::new("run.skip-commands.be-accepted-for-run", "run.skip_commands_should_be_accepted_for_run", &["#treeboot-run"]), ported::run::skip_commands_should_be_accepted_for_run),
    CaseDefinition::new(CaseMetadata::new("run.plan-json.report-pending-files-without-mutation", "run.plan_json_should_report_pending_files_without_mutation", &["#treeboot-plan-and-structured-treeboot-run"]), ported::run::plan_json_should_report_pending_files_without_mutation),
    CaseDefinition::new(CaseMetadata::new("run.plan-yaml.match-json-shape", "run.plan_yaml_should_match_json_shape", &["#treeboot-plan-and-structured-treeboot-run"]), ported::run::plan_yaml_should_match_json_shape),
    CaseDefinition::new(CaseMetadata::new("run.structured-file-only.apply-without-spawning-commands", "run.structured_file_only_run_should_apply_without_spawning_commands", &["#treeboot-plan-and-structured-treeboot-run"]), ported::run::structured_file_only_run_should_apply_without_spawning_commands),
    CaseDefinition::new(CaseMetadata::new("run.implicit-structured-dry-run.include-commands-without-effects", "run.implicit_structured_dry_run_should_include_commands_without_effects", &["#treeboot-plan-and-structured-treeboot-run"]), ported::run::implicit_structured_dry_run_should_include_commands_without_effects),
    CaseDefinition::new(CaseMetadata::new("run.structured-output-validation.precede-discovery", "run.structured_output_validation_should_precede_discovery", &["#treeboot-plan-and-structured-treeboot-run"]), ported::run::structured_output_validation_should_precede_discovery),
    CaseDefinition::new(CaseMetadata::new("run.structured-planning-error.leave-stdout-empty-and-files-unmodified", "run.structured_run_planning_error_should_leave_stdout_empty_and_files_unmodified", &["#treeboot-plan-and-structured-treeboot-run"]), ported::run::structured_run_planning_error_should_leave_stdout_empty_and_files_unmodified),
    CaseDefinition::new(CaseMetadata::new("run.structured-views.share-mixed-file-decisions", "run.structured_views_should_share_mixed_file_decisions", &["#treeboot-plan-and-structured-treeboot-run"]), ported::run::structured_views_should_share_mixed_file_decisions),
    CaseDefinition::new(CaseMetadata::new("run.plan-structured-noops-and-validation-warnings.are-explicit", "run.plan_structured_noops_and_validation_warnings_should_be_explicit", &["#treeboot-plan-and-structured-treeboot-run"]), ported::run::plan_structured_noops_and_validation_warnings_should_be_explicit),
    CaseDefinition::new(CaseMetadata::new("run.structured-mode-combinations-and-text-verbose-plan.are-supported", "run.structured_mode_combinations_and_text_verbose_plan_should_be_supported", &["#treeboot-plan-and-structured-treeboot-run"]), ported::run::structured_mode_combinations_and_text_verbose_plan_should_be_supported),
    #[cfg(target_os = "linux")]
    CaseDefinition::new(CaseMetadata::new("run.plan-text-support-non-utf8-worktrees-while-structured-output-fails-atomically", "run.plan_text_should_support_non_utf8_worktrees_while_structured_output_fails_atomically", &["#treeboot-plan-and-structured-treeboot-run"]), ported::run::plan_text_should_support_non_utf8_worktrees_while_structured_output_fails_atomically),
    #[cfg(not(target_os = "linux"))]
    CaseDefinition::skipped(CaseMetadata::new("run.plan-text-support-non-utf8-worktrees-while-structured-output-fails-atomically", "run.plan_text_should_support_non_utf8_worktrees_while_structured_output_fails_atomically", &["#treeboot-plan-and-structured-treeboot-run"]), "requires Linux because the case uses a non-UTF-8 Git worktree path"),
    #[cfg(target_os = "linux")]
    CaseDefinition::new(CaseMetadata::new("run.structured-execute-failure.keep-stdout-empty-and-prior-effects-only", "run.structured_execute_failure_should_keep_stdout_empty_and_prior_effects_only", &["#treeboot-plan-and-structured-treeboot-run"]), ported::run::structured_execute_failure_should_keep_stdout_empty_and_prior_effects_only),
    #[cfg(not(target_os = "linux"))]
    CaseDefinition::skipped(CaseMetadata::new("run.structured-execute-failure.keep-stdout-empty-and-prior-effects-only", "run.structured_execute_failure_should_keep_stdout_empty_and_prior_effects_only", &["#treeboot-plan-and-structured-treeboot-run"]), "requires Linux procfs where /proc/self/mem is an openable regular file whose offset-zero read fails"),
    CaseDefinition::new(CaseMetadata::new("run.strict-missing-config.exit-with-runtime-failure", "run.strict_missing_config_should_exit_with_runtime_failure", &["#treeboot-run"]), ported::run::strict_missing_config_should_exit_with_runtime_failure),
    CaseDefinition::new(CaseMetadata::new("run.env-strict-missing-config.exit-with-runtime-failure", "run.env_strict_missing_config_should_exit_with_runtime_failure", &["#treeboot-run"]), ported::run::env_strict_missing_config_should_exit_with_runtime_failure),
    CaseDefinition::new(CaseMetadata::new("run.strict-root-checkout.exit-with-runtime-failure", "run.strict_root_checkout_should_exit_with_runtime_failure", &["#treeboot-run"]), ported::run::strict_root_checkout_should_exit_with_runtime_failure),
    CaseDefinition::new(CaseMetadata::new("run.env-strict-root-checkout.exit-with-runtime-failure", "run.env_strict_root_checkout_should_exit_with_runtime_failure", &["#treeboot-run"]), ported::run::env_strict_root_checkout_should_exit_with_runtime_failure),
    CaseDefinition::new(CaseMetadata::new("run.root-checkout.skip-config-detection", "run.root_checkout_should_skip_config_detection", &["#treeboot-run"]), ported::run::root_checkout_should_skip_config_detection),
    #[cfg(unix)]
    CaseDefinition::new(CaseMetadata::new("run.root-checkout.ignore-legacy-scripts-and-skip-config", "run.root_checkout_should_ignore_legacy_scripts_and_skip_config", &["#treeboot-run"]), ported::run::root_checkout_should_ignore_legacy_scripts_and_skip_config),
    #[cfg(not(unix))]
    CaseDefinition::skipped(CaseMetadata::new("run.root-checkout.ignore-legacy-scripts-and-skip-config", "run.root_checkout_should_ignore_legacy_scripts_and_skip_config", &["#treeboot-run"]), "requires a Unix host"),
    CaseDefinition::new(CaseMetadata::new("run.outside-git-worktree.exit-with-runtime-failure", "run.run_outside_git_worktree_should_exit_with_runtime_failure", &["#treeboot-run"]), ported::run::run_outside_git_worktree_should_exit_with_runtime_failure),
    #[cfg(unix)]
    CaseDefinition::new(CaseMetadata::new("run.command-only-config.execute-from-worktree", "run.run_command_only_config_should_execute_from_worktree", &["#treeboot-run"]), ported::run::run_command_only_config_should_execute_from_worktree),
    #[cfg(not(unix))]
    CaseDefinition::skipped(CaseMetadata::new("run.command-only-config.execute-from-worktree", "run.run_command_only_config_should_execute_from_worktree", &["#treeboot-run"]), "requires a Unix host"),
    #[cfg(unix)]
    CaseDefinition::new(CaseMetadata::new("run.should-reject-command-cwd-escaped-by-preceding-symlink", "run.run_should_reject_command_cwd_escaped_by_preceding_symlink", &["#treeboot-run"]), ported::run::run_should_reject_command_cwd_escaped_by_preceding_symlink),
    #[cfg(not(unix))]
    CaseDefinition::skipped(CaseMetadata::new("run.should-reject-command-cwd-escaped-by-preceding-symlink", "run.run_should_reject_command_cwd_escaped_by_preceding_symlink", &["#treeboot-run"]), "requires a Unix host"),
    CaseDefinition::new(CaseMetadata::new("run.should-reject-command-cwd-symlink-retargeted-after-planning", "run.run_should_reject_command_cwd_symlink_retargeted_after_planning", &["#treeboot-run"]), ported::run::run_should_reject_command_cwd_symlink_retargeted_after_planning),
    CaseDefinition::new(CaseMetadata::new("run.should-apply-configured-file-ignore-patterns", "run.run_should_apply_configured_file_ignore_patterns", &["#treeboot-run"]), ported::run::run_should_apply_configured_file_ignore_patterns),
    CaseDefinition::new(CaseMetadata::new("run.invalid-config.exit-with-config-error", "run.run_invalid_config_should_exit_with_config_error", &["#treeboot-run"]), ported::run::run_invalid_config_should_exit_with_config_error),
    CaseDefinition::new(CaseMetadata::new("run.duplicate-file-targets.exit-with-config-error", "run.run_duplicate_file_targets_should_exit_with_config_error", &["#treeboot-run"]), ported::run::run_duplicate_file_targets_should_exit_with_config_error),
    CaseDefinition::new(CaseMetadata::new("run.overlapping-sync-delete-targets.fail-before-side-effects", "run.run_overlapping_sync_delete_targets_should_fail_before_side_effects", &["#treeboot-run"]), ported::run::run_overlapping_sync_delete_targets_should_fail_before_side_effects),
    CaseDefinition::new(CaseMetadata::new("run.target-outside-worktree.exit-with-config-error", "run.run_target_outside_worktree_should_exit_with_config_error", &["#treeboot-run"]), ported::run::run_target_outside_worktree_should_exit_with_config_error),
    CaseDefinition::new(CaseMetadata::new("run.source-outside-root.exit-with-config-error", "run.run_source_outside_root_should_exit_with_config_error", &["#treeboot-run"]), ported::run::run_source_outside_root_should_exit_with_config_error),
    CaseDefinition::new(CaseMetadata::new("run.required-missing-source.exit-with-config-error", "run.run_required_missing_source_should_exit_with_config_error", &["#treeboot-run"]), ported::run::run_required_missing_source_should_exit_with_config_error),
    CaseDefinition::new(CaseMetadata::new("run.strict-sync.exit-with-config-error", "run.run_strict_sync_should_exit_with_config_error", &["#treeboot-run"]), ported::run::run_strict_sync_should_exit_with_config_error),
    CaseDefinition::new(CaseMetadata::new("run.config-strict-sync.exit-with-config-error", "run.run_config_strict_sync_should_exit_with_config_error", &["#treeboot-run"]), ported::run::run_config_strict_sync_should_exit_with_config_error),
    CaseDefinition::new(CaseMetadata::new("run.env-false.override-config-strict", "run.run_env_false_should_override_config_strict", &["#treeboot-run"]), ported::run::run_env_false_should_override_config_strict),
    CaseDefinition::new(CaseMetadata::new("run.cli-strict.override-env-false", "run.run_cli_strict_should_override_env_false", &["#treeboot-run"]), ported::run::run_cli_strict_should_override_env_false),
    CaseDefinition::new(CaseMetadata::new("run.config-dangerous-source-option.allow-outside-source", "run.run_config_dangerous_source_option_should_allow_outside_source", &["#treeboot-run"]), ported::run::run_config_dangerous_source_option_should_allow_outside_source),
    CaseDefinition::new(CaseMetadata::new("run.env-dangerous-target-option.allow-outside-target", "run.run_env_dangerous_target_option_should_allow_outside_target", &["#treeboot-run"]), ported::run::run_env_dangerous_target_option_should_allow_outside_target),
    CaseDefinition::new(CaseMetadata::new("run.should-accept-absolute-paths-inside-root-and-worktree", "run.run_should_accept_absolute_paths_inside_root_and_worktree", &["#treeboot-run"]), ported::run::run_should_accept_absolute_paths_inside_root_and_worktree),
    CaseDefinition::new(CaseMetadata::new("run.dangerous-source-option.allow-symlink-to-outside-source", "run.run_dangerous_source_option_should_allow_symlink_to_outside_source", &["#treeboot-run"]), ported::run::run_dangerous_source_option_should_allow_symlink_to_outside_source),
    CaseDefinition::new(CaseMetadata::new("run.dangerous-source-option.allow-existing-symlink-to-outside-source", "run.run_dangerous_source_option_should_allow_existing_symlink_to_outside_source", &["#treeboot-run"]), ported::run::run_dangerous_source_option_should_allow_existing_symlink_to_outside_source),
    CaseDefinition::new(CaseMetadata::new("run.dangerous-target-option.allow-symlink-outside-worktree", "run.run_dangerous_target_option_should_allow_symlink_outside_worktree", &["#treeboot-run"]), ported::run::run_dangerous_target_option_should_allow_symlink_outside_worktree),
    CaseDefinition::new(CaseMetadata::new("run.dangerous-target-option.allow-existing-symlink-outside-worktree", "run.run_dangerous_target_option_should_allow_existing_symlink_outside_worktree", &["#treeboot-run"]), ported::run::run_dangerous_target_option_should_allow_existing_symlink_outside_worktree),
    CaseDefinition::new(CaseMetadata::new("run.symlink.reject-target-parent-symlink-to-root-subdirectory", "run.run_symlink_should_reject_target_parent_symlink_to_root_subdirectory", &["#treeboot-run"]), ported::run::run_symlink_should_reject_target_parent_symlink_to_root_subdirectory),
    CaseDefinition::new(CaseMetadata::new("run.symlink.reject-target-parent-file-in-subdirectory", "run.run_symlink_should_reject_target_parent_file_in_subdirectory", &["#treeboot-run"]), ported::run::run_symlink_should_reject_target_parent_file_in_subdirectory),
    CaseDefinition::new(CaseMetadata::new("run.copy.reject-target-parent-symlink-to-root-subdirectory", "run.run_copy_should_reject_target_parent_symlink_to_root_subdirectory", &["#treeboot-run"]), ported::run::run_copy_should_reject_target_parent_symlink_to_root_subdirectory),
    CaseDefinition::new(CaseMetadata::new("run.copy.reject-target-parent-file-in-subdirectory", "run.run_copy_should_reject_target_parent_file_in_subdirectory", &["#treeboot-run"]), ported::run::run_copy_should_reject_target_parent_file_in_subdirectory),
    CaseDefinition::new(CaseMetadata::new("run.sync.reject-target-parent-symlink-to-root-subdirectory", "run.run_sync_should_reject_target_parent_symlink_to_root_subdirectory", &["#treeboot-run"]), ported::run::run_sync_should_reject_target_parent_symlink_to_root_subdirectory),
    CaseDefinition::new(CaseMetadata::new("run.sync.reject-target-parent-file-in-subdirectory", "run.run_sync_should_reject_target_parent_file_in_subdirectory", &["#treeboot-run"]), ported::run::run_sync_should_reject_target_parent_file_in_subdirectory),
    CaseDefinition::new(CaseMetadata::new("run.default-symlink.skip-existing-mismatched-subdirectory-symlink", "run.run_default_symlink_should_skip_existing_mismatched_subdirectory_symlink", &["#treeboot-run"]), ported::run::run_default_symlink_should_skip_existing_mismatched_subdirectory_symlink),
    CaseDefinition::new(CaseMetadata::new("run.strict-existing-subdirectory-symlink.fail-before-mutation", "run.run_strict_existing_subdirectory_symlink_should_fail_before_mutation", &["#treeboot-run"]), ported::run::run_strict_existing_subdirectory_symlink_should_fail_before_mutation),
    CaseDefinition::new(CaseMetadata::new("run.force.replace-existing-subdirectory-symlink", "run.run_force_should_replace_existing_subdirectory_symlink", &["#treeboot-run"]), ported::run::run_force_should_replace_existing_subdirectory_symlink),
    CaseDefinition::new(CaseMetadata::new("run.default-symlink.skip-broken-existing-subdirectory-symlink", "run.run_default_symlink_should_skip_broken_existing_subdirectory_symlink", &["#treeboot-run"]), ported::run::run_default_symlink_should_skip_broken_existing_subdirectory_symlink),
    CaseDefinition::new(CaseMetadata::new("run.dry-run-symlink.handle-existing-and-missing-subdirectory-targets", "run.run_dry_run_symlink_should_handle_existing_and_missing_subdirectory_targets", &["#treeboot-run"]), ported::run::run_dry_run_symlink_should_handle_existing_and_missing_subdirectory_targets),
    CaseDefinition::new(CaseMetadata::new("run.dangerous-source-option.skip-optional-missing-outside-symlink-source", "run.run_dangerous_source_option_should_skip_optional_missing_outside_symlink_source", &["#treeboot-run"]), ported::run::run_dangerous_source_option_should_skip_optional_missing_outside_symlink_source),
    CaseDefinition::new(CaseMetadata::new("run.dangerous-source-option.reject-required-missing-outside-symlink-source", "run.run_dangerous_source_option_should_reject_required_missing_outside_symlink_source", &["#treeboot-run"]), ported::run::run_dangerous_source_option_should_reject_required_missing_outside_symlink_source),
    CaseDefinition::new(CaseMetadata::new("run.dangerous-target-option.create-nested-parent-dirs-outside-worktree", "run.run_dangerous_target_option_should_create_nested_parent_dirs_outside_worktree", &["#treeboot-run"]), ported::run::run_dangerous_target_option_should_create_nested_parent_dirs_outside_worktree),
    CaseDefinition::new(CaseMetadata::new("run.dangerous-target-option.reject-existing-directory-target-outside-worktree", "run.run_dangerous_target_option_should_reject_existing_directory_target_outside_worktree", &["#treeboot-run"]), ported::run::run_dangerous_target_option_should_reject_existing_directory_target_outside_worktree),
    CaseDefinition::new(CaseMetadata::new("run.invalid-boolean-env.fail-before-config-discovery", "run.run_invalid_boolean_env_should_fail_before_config_discovery", &["#treeboot-run"]), ported::run::run_invalid_boolean_env_should_fail_before_config_discovery),
    CaseDefinition::new(CaseMetadata::new("run.command-cwd-outside-worktree.exit-with-config-error", "run.run_command_cwd_outside_worktree_should_exit_with_config_error", &["#treeboot-run"]), ported::run::run_command_cwd_outside_worktree_should_exit_with_config_error),
    CaseDefinition::new(CaseMetadata::new("run.command-env-owned-override.exit-with-config-error", "run.run_command_env_owned_override_should_exit_with_config_error", &["#treeboot-run"]), ported::run::run_command_env_owned_override_should_exit_with_config_error),
    CaseDefinition::new(CaseMetadata::new("run.worktree-identity-overrides.fail-before-file-effects", "run.run_worktree_identity_overrides_should_fail_before_file_effects", &["#treeboot-run"]), ported::run::run_worktree_identity_overrides_should_fail_before_file_effects),
    CaseDefinition::new(CaseMetadata::new("run.unsafe-source-symlink.exit-with-config-error", "run.run_unsafe_source_symlink_should_exit_with_config_error", &["#treeboot-run"]), ported::run::run_unsafe_source_symlink_should_exit_with_config_error),
    CaseDefinition::new(CaseMetadata::new("run.file-only-config.copy-file", "run.run_file_only_config_should_copy_file", &["#treeboot-run"]), ported::run::run_file_only_config_should_copy_file),
    CaseDefinition::new(CaseMetadata::new("run.optional-missing-source.report-skip", "run.run_optional_missing_source_should_report_skip", &["#treeboot-run"]), ported::run::run_optional_missing_source_should_report_skip),
    #[cfg(unix)]
    CaseDefinition::new(CaseMetadata::new("run.config-with-commands.apply-files-before-commands", "run.run_config_with_commands_should_apply_files_before_commands", &["#treeboot-run"]), ported::run::run_config_with_commands_should_apply_files_before_commands),
    #[cfg(not(unix))]
    CaseDefinition::skipped(CaseMetadata::new("run.config-with-commands.apply-files-before-commands", "run.run_config_with_commands_should_apply_files_before_commands", &["#treeboot-run"]), "requires a Unix host"),
    #[cfg(unix)]
    CaseDefinition::new(CaseMetadata::new("run.file-failure.prevent-command-execution", "run.run_file_failure_should_prevent_command_execution", &["#treeboot-run"]), ported::run::run_file_failure_should_prevent_command_execution),
    #[cfg(not(unix))]
    CaseDefinition::skipped(CaseMetadata::new("run.file-failure.prevent-command-execution", "run.run_file_failure_should_prevent_command_execution", &["#treeboot-run"]), "requires a Unix host"),
    CaseDefinition::new(CaseMetadata::new("run.sync-config.copy-then-sync", "run.run_sync_config_should_copy_then_sync", &["#treeboot-run"]), ported::run::run_sync_config_should_copy_then_sync),
    CaseDefinition::new(CaseMetadata::new("run.verbose-sync.report-concrete-file-actions", "run.run_verbose_sync_should_report_concrete_file_actions", &["#treeboot-run"]), ported::run::run_verbose_sync_should_report_concrete_file_actions),
    CaseDefinition::new(CaseMetadata::new("run.sync-delete.remove-target-only-file", "run.run_sync_delete_should_remove_target_only_file", &["#treeboot-run"]), ported::run::run_sync_delete_should_remove_target_only_file),
    CaseDefinition::new(CaseMetadata::new("run.sync-delete.preserve-default-ignored-target-only-file", "run.run_sync_delete_should_preserve_default_ignored_target_only_file", &["#treeboot-run"]), ported::run::run_sync_delete_should_preserve_default_ignored_target_only_file),
    CaseDefinition::new(CaseMetadata::new("run.sync.preserve-target-only-file-by-default", "run.run_sync_should_preserve_target_only_file_by_default", &["#treeboot-run"]), ported::run::run_sync_should_preserve_target_only_file_by_default),
    CaseDefinition::new(CaseMetadata::new("run.dry-run-sync-delete.not-remove-target-only-file", "run.run_dry_run_sync_delete_should_not_remove_target_only_file", &["#treeboot-run"]), ported::run::run_dry_run_sync_delete_should_not_remove_target_only_file),
    #[cfg(unix)]
    CaseDefinition::new(CaseMetadata::new("run.dry-run-sync-metadata.not-mutate-directory-permissions", "run.run_dry_run_sync_metadata_should_not_mutate_directory_permissions", &["#treeboot-run"]), ported::run::run_dry_run_sync_metadata_should_not_mutate_directory_permissions),
    #[cfg(not(unix))]
    CaseDefinition::skipped(CaseMetadata::new("run.dry-run-sync-metadata.not-mutate-directory-permissions", "run.run_dry_run_sync_metadata_should_not_mutate_directory_permissions", &["#treeboot-run"]), "requires a Unix host"),
    CaseDefinition::new(CaseMetadata::new("run.checksum-sync.update-when-metadata-matches", "run.run_checksum_sync_should_update_when_metadata_matches", &["#treeboot-run"]), ported::run::run_checksum_sync_should_update_when_metadata_matches),
    CaseDefinition::new(CaseMetadata::new("run.config-with-commands-and-skip-commands.copy-file", "run.run_config_with_commands_and_skip_commands_should_copy_file", &["#treeboot-run"]), ported::run::run_config_with_commands_and_skip_commands_should_copy_file),
    #[cfg(unix)]
    CaseDefinition::new(CaseMetadata::new("run.skip-commands.not-spawn-failing-command", "run.run_skip_commands_should_not_spawn_failing_command", &["#treeboot-run"]), ported::run::run_skip_commands_should_not_spawn_failing_command),
    #[cfg(not(unix))]
    CaseDefinition::skipped(CaseMetadata::new("run.skip-commands.not-spawn-failing-command", "run.run_skip_commands_should_not_spawn_failing_command", &["#treeboot-run"]), "requires a Unix host"),
    #[cfg(unix)]
    CaseDefinition::new(CaseMetadata::new("run.dry-run.report-files-and-commands-without-side-effects", "run.run_dry_run_should_report_files_and_commands_without_side_effects", &["#treeboot-run"]), ported::run::run_dry_run_should_report_files_and_commands_without_side_effects),
    #[cfg(not(unix))]
    CaseDefinition::skipped(CaseMetadata::new("run.dry-run.report-files-and-commands-without-side-effects", "run.run_dry_run_should_report_files_and_commands_without_side_effects", &["#treeboot-run"]), "requires a Unix host"),
    #[cfg(unix)]
    CaseDefinition::new(CaseMetadata::new("run.commands.isolate-env-and-honor-cwd", "run.run_commands_should_isolate_env_and_honor_cwd", &["#treeboot-run"]), ported::run::run_commands_should_isolate_env_and_honor_cwd),
    #[cfg(not(unix))]
    CaseDefinition::skipped(CaseMetadata::new("run.commands.isolate-env-and-honor-cwd", "run.run_commands_should_isolate_env_and_honor_cwd", &["#treeboot-run"]), "requires a Unix host"),
    #[cfg(unix)]
    CaseDefinition::new(CaseMetadata::new("run.direct-program-args.preserve-argument-boundaries", "run.run_direct_program_args_should_preserve_argument_boundaries", &["#treeboot-run"]), ported::run::run_direct_program_args_should_preserve_argument_boundaries),
    #[cfg(not(unix))]
    CaseDefinition::skipped(CaseMetadata::new("run.direct-program-args.preserve-argument-boundaries", "run.run_direct_program_args_should_preserve_argument_boundaries", &["#treeboot-run"]), "requires a Unix host"),
    #[cfg(unix)]
    CaseDefinition::new(CaseMetadata::new("run.should-reject-async-command-field", "run.run_should_reject_async_command_field", &["#treeboot-run"]), ported::run::run_should_reject_async_command_field),
    #[cfg(not(unix))]
    CaseDefinition::skipped(CaseMetadata::new("run.should-reject-async-command-field", "run.run_should_reject_async_command_field", &["#treeboot-run"]), "requires a Unix host"),
    #[cfg(unix)]
    CaseDefinition::new(CaseMetadata::new("run.fatal-command-failure.keep-file-side-effects-and-stop-later-commands", "run.run_fatal_command_failure_should_keep_file_side_effects_and_stop_later_commands", &["#treeboot-run"]), ported::run::run_fatal_command_failure_should_keep_file_side_effects_and_stop_later_commands),
    #[cfg(not(unix))]
    CaseDefinition::skipped(CaseMetadata::new("run.fatal-command-failure.keep-file-side-effects-and-stop-later-commands", "run.run_fatal_command_failure_should_keep_file_side_effects_and_stop_later_commands", &["#treeboot-run"]), "requires a Unix host"),
    #[cfg(unix)]
    CaseDefinition::new(CaseMetadata::new("run.allowed-command-failure.warn-and-continue", "run.run_allowed_command_failure_should_warn_and_continue", &["#treeboot-run"]), ported::run::run_allowed_command_failure_should_warn_and_continue),
    #[cfg(not(unix))]
    CaseDefinition::skipped(CaseMetadata::new("run.allowed-command-failure.warn-and-continue", "run.run_allowed_command_failure_should_warn_and_continue", &["#treeboot-run"]), "requires a Unix host"),
    #[cfg(unix)]
    CaseDefinition::new(CaseMetadata::new("run.fatal-spawn-failure.exit-nonzero", "run.run_fatal_spawn_failure_should_exit_nonzero", &["#treeboot-run"]), ported::run::run_fatal_spawn_failure_should_exit_nonzero),
    #[cfg(not(unix))]
    CaseDefinition::skipped(CaseMetadata::new("run.fatal-spawn-failure.exit-nonzero", "run.run_fatal_spawn_failure_should_exit_nonzero", &["#treeboot-run"]), "requires a Unix host"),
    CaseDefinition::new(CaseMetadata::new("run.sync-config-with-commands-and-skip-commands.sync-file", "run.run_sync_config_with_commands_and_skip_commands_should_sync_file", &["#treeboot-run"]), ported::run::run_sync_config_with_commands_and_skip_commands_should_sync_file),
    CaseDefinition::new(CaseMetadata::new("run.strict-existing-copy-target.fail-before-mutation", "run.run_strict_existing_copy_target_should_fail_before_mutation", &["#treeboot-run"]), ported::run::run_strict_existing_copy_target_should_fail_before_mutation),
    CaseDefinition::new(CaseMetadata::new("run.force-copy.replace-existing-target", "run.run_force_copy_should_replace_existing_target", &["#treeboot-run"]), ported::run::run_force_copy_should_replace_existing_target),
    CaseDefinition::new(CaseMetadata::new("run.dry-run-copy.not-mutate-target", "run.run_dry_run_copy_should_not_mutate_target", &["#treeboot-run"]), ported::run::run_dry_run_copy_should_not_mutate_target),
    CaseDefinition::new(CaseMetadata::new("run.default-copy.skip-existing-target", "run.run_default_copy_should_skip_existing_target", &["#treeboot-run"]), ported::run::run_default_copy_should_skip_existing_target),
    CaseDefinition::new(CaseMetadata::new("run.copied-symlink.warn-when-final-target-is-missing", "run.run_copied_symlink_should_warn_when_final_target_is_missing", &["#treeboot-run"]), ported::run::run_copied_symlink_should_warn_when_final_target_is_missing),
    CaseDefinition::new(CaseMetadata::new("run.symlink.create-relative-symlink", "run.run_symlink_should_create_relative_symlink", &["#treeboot-run"]), ported::run::run_symlink_should_create_relative_symlink),
    CaseDefinition::new(CaseMetadata::new("run.symlink.allow-existing-link-to-root-source-in-subdirectory", "run.run_symlink_should_allow_existing_link_to_root_source_in_subdirectory", &["#treeboot-run"]), ported::run::run_symlink_should_allow_existing_link_to_root_source_in_subdirectory),
    CaseDefinition::new(CaseMetadata::new("run.file-operations.apply-sources-in-subdirectories", "run.run_file_operations_should_apply_sources_in_subdirectories", &["#treeboot-run"]), ported::run::run_file_operations_should_apply_sources_in_subdirectories),
    #[cfg(unix)]
    CaseDefinition::new(CaseMetadata::new("run.root-option.set-configured-command-root-env", "run.root_option_should_set_configured_command_root_env", &["#treeboot-run"]), ported::run::root_option_should_set_configured_command_root_env),
    #[cfg(not(unix))]
    CaseDefinition::skipped(CaseMetadata::new("run.root-option.set-configured-command-root-env", "run.root_option_should_set_configured_command_root_env", &["#treeboot-run"]), "requires a Unix host"),
    #[cfg(unix)]
    CaseDefinition::new(CaseMetadata::new("run.conductor-default-branch-env.set-configured-command-branch-env", "run.conductor_default_branch_env_should_set_configured_command_branch_env", &["#treeboot-run"]), ported::run::conductor_default_branch_env_should_set_configured_command_branch_env),
    #[cfg(not(unix))]
    CaseDefinition::skipped(CaseMetadata::new("run.conductor-default-branch-env.set-configured-command-branch-env", "run.conductor_default_branch_env_should_set_configured_command_branch_env", &["#treeboot-run"]), "requires a Unix host"),
    #[cfg(unix)]
    CaseDefinition::new(CaseMetadata::new("run.executable-legacy-scripts.not-run-or-override-config", "run.executable_legacy_scripts_should_not_run_or_override_config", &["#treeboot-run"]), ported::run::executable_legacy_scripts_should_not_run_or_override_config),
    #[cfg(not(unix))]
    CaseDefinition::skipped(CaseMetadata::new("run.executable-legacy-scripts.not-run-or-override-config", "run.executable_legacy_scripts_should_not_run_or_override_config", &["#treeboot-run"]), "requires a Unix host"),
    #[cfg(unix)]
    CaseDefinition::new(CaseMetadata::new("run.executable-legacy-script-only-repo.follow-missing-config-behavior", "run.executable_legacy_script_only_repo_should_follow_missing_config_behavior", &["#treeboot-run"]), ported::run::executable_legacy_script_only_repo_should_follow_missing_config_behavior),
    #[cfg(not(unix))]
    CaseDefinition::skipped(CaseMetadata::new("run.executable-legacy-script-only-repo.follow-missing-config-behavior", "run.executable_legacy_script_only_repo_should_follow_missing_config_behavior", &["#treeboot-run"]), "requires a Unix host"),
    #[cfg(unix)]
    CaseDefinition::new(CaseMetadata::new("run.executable-legacy-script-only-repo.fail-in-strict-mode", "run.executable_legacy_script_only_repo_should_fail_in_strict_mode", &["#treeboot-run"]), ported::run::executable_legacy_script_only_repo_should_fail_in_strict_mode),
    #[cfg(not(unix))]
    CaseDefinition::skipped(CaseMetadata::new("run.executable-legacy-script-only-repo.fail-in-strict-mode", "run.executable_legacy_script_only_repo_should_fail_in_strict_mode", &["#treeboot-run"]), "requires a Unix host"),
    #[cfg(unix)]
    CaseDefinition::new(CaseMetadata::new("run.config-option.ignore-executable-legacy-script", "run.config_option_should_ignore_executable_legacy_script", &["#treeboot-run"]), ported::run::config_option_should_ignore_executable_legacy_script),
    #[cfg(not(unix))]
    CaseDefinition::skipped(CaseMetadata::new("run.config-option.ignore-executable-legacy-script", "run.config_option_should_ignore_executable_legacy_script", &["#treeboot-run"]), "requires a Unix host"),
    CaseDefinition::new(CaseMetadata::new("run.no-init-script-top-level-flag.be-usage-error", "run.no_init_script_top_level_flag_should_be_usage_error", &["#treeboot-run"]), ported::run::no_init_script_top_level_flag_should_be_usage_error),
    CaseDefinition::new(CaseMetadata::new("run.no-init-script-run-flag.be-usage-error", "run.no_init_script_run_flag_should_be_usage_error", &["#treeboot-run"]), ported::run::no_init_script_run_flag_should_be_usage_error),
    CaseDefinition::new(CaseMetadata::new("run.should-apply-config-include-filters", "run.run_should_apply_config_include_filters", &["#treeboot-run"]), ported::run::run_should_apply_config_include_filters),
    CaseDefinition::new(CaseMetadata::new("run.should-stay-silent-on-zero-match-include", "run.run_should_stay_silent_on_zero_match_include", &["#treeboot-run"]), ported::run::run_should_stay_silent_on_zero_match_include),
    CaseDefinition::new(CaseMetadata::new("run.should-reject-include-with-sync-delete-before-side-effects", "run.run_should_reject_include_with_sync_delete_before_side_effects", &["#treeboot-run"]), ported::run::run_should_reject_include_with_sync_delete_before_side_effects),
    CaseDefinition::new(CaseMetadata::new("schema.should-print-or-write-embedded-schema", "schema.schema_should_print_or_write_embedded_schema", &["#treeboot-schema"]), ported::schema::schema_should_print_or_write_embedded_schema),
    CaseDefinition::new(CaseMetadata::new("schema.output-short-flag.write-file", "schema.schema_output_short_flag_should_write_file", &["#treeboot-schema"]), ported::schema::schema_output_short_flag_should_write_file),
    CaseDefinition::new(CaseMetadata::new("schema.should-fail-when-output-parent-is-missing", "schema.schema_should_fail_when_output_parent_is_missing", &["#treeboot-schema"]), ported::schema::schema_should_fail_when_output_parent_is_missing),
    CaseDefinition::new(CaseMetadata::new("schema.should-not-accept-report-format-options", "schema.schema_should_not_accept_report_format_options", &["#treeboot-schema"]), ported::schema::schema_should_not_accept_report_format_options),
    CaseDefinition::new(CaseMetadata::new("status.should-report-worktree-root-and-config-without-parsing", "status.status_should_report_worktree_root_and_config_without_parsing", &["#treeboot-status"]), ported::status::status_should_report_worktree_root_and_config_without_parsing),
    CaseDefinition::new(CaseMetadata::new("status.should-support-json-yaml-and-text-formats", "status.status_should_support_json_yaml_and_text_formats", &["#treeboot-status"]), ported::status::status_should_support_json_yaml_and_text_formats),
    CaseDefinition::new(CaseMetadata::new("status.info-alias.report-status", "status.info_alias_should_report_status", &["#treeboot-status"]), ported::status::info_alias_should_report_status),
    CaseDefinition::new(CaseMetadata::new("status.no-init-script.be-usage-error", "status.status_no_init_script_should_be_usage_error", &["#treeboot-status"]), ported::status::status_no_init_script_should_be_usage_error),
    CaseDefinition::new(CaseMetadata::new("status.should-report-default-branch-from-environment", "status.status_should_report_default_branch_from_environment", &["#treeboot-status"]), ported::status::status_should_report_default_branch_from_environment),
    CaseDefinition::new(CaseMetadata::new("status.output-shortcuts.conflict-with-format", "status.status_output_shortcuts_should_conflict_with_format", &["#treeboot-status"]), ported::status::status_output_shortcuts_should_conflict_with_format),
    CaseDefinition::new(CaseMetadata::new("status.should-fail-outside-git-worktree", "status.status_should_fail_outside_git_worktree", &["#treeboot-status"]), ported::status::status_should_fail_outside_git_worktree),
    CaseDefinition::new(CaseMetadata::new("status.config-option.report-requested-config", "status.status_config_option_should_report_requested_config", &["#treeboot-status"]), ported::status::status_config_option_should_report_requested_config),
    #[cfg(unix)]
    CaseDefinition::new(CaseMetadata::new("status.json.ignore-legacy-script-file", "status.status_json_should_ignore_legacy_script_file", &["#treeboot-status"]), ported::status::status_json_should_ignore_legacy_script_file),
    #[cfg(not(unix))]
    CaseDefinition::skipped(CaseMetadata::new("status.json.ignore-legacy-script-file", "status.status_json_should_ignore_legacy_script_file", &["#treeboot-status"]), "requires a Unix host"),
    CaseDefinition::new(CaseMetadata::new("teardown.should-reject-root-checkout", "teardown.teardown_should_reject_root_checkout", &["#treeboot-teardown"]), ported::teardown::teardown_should_reject_root_checkout),
    CaseDefinition::new(CaseMetadata::new("teardown.should-reject-actual-root-with-explicit-source-root-override", "teardown.teardown_should_reject_actual_root_with_explicit_source_root_override", &["#treeboot-teardown"]), ported::teardown::teardown_should_reject_actual_root_with_explicit_source_root_override),
    CaseDefinition::new(CaseMetadata::new("teardown.should-reject-actual-root-with-source-root-environment-aliases", "teardown.teardown_should_reject_actual_root_with_source_root_environment_aliases", &["#treeboot-teardown"]), ported::teardown::teardown_should_reject_actual_root_with_source_root_environment_aliases),
    CaseDefinition::new(CaseMetadata::new("teardown.should-noop-when-discovered-config-is-missing", "teardown.teardown_should_noop_when_discovered_config_is_missing", &["#treeboot-teardown"]), ported::teardown::teardown_should_noop_when_discovered_config_is_missing),
    CaseDefinition::new(CaseMetadata::new("teardown.should-fail-when-requested-config-is-missing", "teardown.teardown_should_fail_when_requested_config_is_missing", &["#treeboot-teardown"]), ported::teardown::teardown_should_fail_when_requested_config_is_missing),
    CaseDefinition::new(CaseMetadata::new("teardown.should-noop-without-configured-commands", "teardown.teardown_should_noop_without_configured_commands", &["#treeboot-teardown"]), ported::teardown::teardown_should_noop_without_configured_commands),
    CaseDefinition::new(CaseMetadata::new("teardown.should-require-yes-when-input-is-not-a-terminal", "teardown.teardown_should_require_yes_when_input_is_not_a_terminal", &["#treeboot-teardown"]), ported::teardown::teardown_should_require_yes_when_input_is_not_a_terminal),
    CaseDefinition::new(CaseMetadata::new("teardown.dry-run.not-require-approval-or-spawn", "teardown.teardown_dry_run_should_not_require_approval_or_spawn", &["#treeboot-teardown"]), ported::teardown::teardown_dry_run_should_not_require_approval_or_spawn),
    #[cfg(unix)]
    CaseDefinition::new(CaseMetadata::new("teardown.yes.run-only-teardown-commands", "teardown.teardown_yes_should_run_only_teardown_commands", &["#treeboot-teardown"]), ported::teardown::teardown_yes_should_run_only_teardown_commands),
    #[cfg(not(unix))]
    CaseDefinition::skipped(CaseMetadata::new("teardown.yes.run-only-teardown-commands", "teardown.teardown_yes_should_run_only_teardown_commands", &["#treeboot-teardown"]), "requires a Unix host"),
    #[cfg(unix)]
    CaseDefinition::new(CaseMetadata::new("teardown.bootstrap-and-teardown-commands.share-worktree-identity-after-branch-rename", "teardown.bootstrap_and_teardown_commands_should_share_worktree_identity_after_branch_rename", &["#treeboot-teardown"]), ported::teardown::bootstrap_and_teardown_commands_should_share_worktree_identity_after_branch_rename),
    #[cfg(not(unix))]
    CaseDefinition::skipped(CaseMetadata::new("teardown.bootstrap-and-teardown-commands.share-worktree-identity-after-branch-rename", "teardown.bootstrap_and_teardown_commands_should_share_worktree_identity_after_branch_rename", &["#treeboot-teardown"]), "requires a Unix host"),
    #[cfg(unix)]
    CaseDefinition::new(CaseMetadata::new("teardown.can-target-linked-worktree-from-root", "teardown.teardown_can_target_linked_worktree_from_root", &["#treeboot-teardown"]), ported::teardown::teardown_can_target_linked_worktree_from_root),
    #[cfg(not(unix))]
    CaseDefinition::skipped(CaseMetadata::new("teardown.can-target-linked-worktree-from-root", "teardown.teardown_can_target_linked_worktree_from_root", &["#treeboot-teardown"]), "requires a Unix host"),
    #[cfg(unix)]
    CaseDefinition::new(CaseMetadata::new("teardown.bootstrap-semantic-failure.not-block-teardown", "teardown.bootstrap_semantic_failure_should_not_block_teardown", &["#treeboot-teardown"]), ported::teardown::bootstrap_semantic_failure_should_not_block_teardown),
    #[cfg(not(unix))]
    CaseDefinition::skipped(CaseMetadata::new("teardown.bootstrap-semantic-failure.not-block-teardown", "teardown.bootstrap_semantic_failure_should_not_block_teardown", &["#treeboot-teardown"]), "requires a Unix host"),
    #[cfg(unix)]
    CaseDefinition::new(CaseMetadata::new("teardown.bootstrap-command-cwd-escape.not-block-teardown", "teardown.bootstrap_command_cwd_escape_should_not_block_teardown", &["#treeboot-teardown"]), ported::teardown::bootstrap_command_cwd_escape_should_not_block_teardown),
    #[cfg(not(unix))]
    CaseDefinition::skipped(CaseMetadata::new("teardown.bootstrap-command-cwd-escape.not-block-teardown", "teardown.bootstrap_command_cwd_escape_should_not_block_teardown", &["#treeboot-teardown"]), "requires a Unix host"),
    CaseDefinition::new(CaseMetadata::new("teardown.whole-config-parse-failure.block-teardown", "teardown.whole_config_parse_failure_should_block_teardown", &["#treeboot-teardown"]), ported::teardown::whole_config_parse_failure_should_block_teardown),
    CaseDefinition::new(CaseMetadata::new("teardown.worktree-identity-overrides.fail-before-any-command", "teardown.teardown_worktree_identity_overrides_should_fail_before_any_command", &["#treeboot-teardown"]), ported::teardown::teardown_worktree_identity_overrides_should_fail_before_any_command),
    CaseDefinition::new(CaseMetadata::new("teardown.should-ignore-bootstrap-strict-environment", "teardown.teardown_should_ignore_bootstrap_strict_environment", &["#treeboot-teardown"]), ported::teardown::teardown_should_ignore_bootstrap_strict_environment),
    #[cfg(unix)]
    CaseDefinition::new(CaseMetadata::new("teardown.should-continue-after-allowed-failure", "teardown.teardown_should_continue_after_allowed_failure", &["#treeboot-teardown"]), ported::teardown::teardown_should_continue_after_allowed_failure),
    #[cfg(not(unix))]
    CaseDefinition::skipped(CaseMetadata::new("teardown.should-continue-after-allowed-failure", "teardown.teardown_should_continue_after_allowed_failure", &["#treeboot-teardown"]), "requires a Unix host"),
    #[cfg(unix)]
    CaseDefinition::new(CaseMetadata::new("teardown.should-stop-after-fatal-failure", "teardown.teardown_should_stop_after_fatal_failure", &["#treeboot-teardown"]), ported::teardown::teardown_should_stop_after_fatal_failure),
    #[cfg(not(unix))]
    CaseDefinition::skipped(CaseMetadata::new("teardown.should-stop-after-fatal-failure", "teardown.teardown_should_stop_after_fatal_failure", &["#treeboot-teardown"]), "requires a Unix host"),
    CaseDefinition::new(CaseMetadata::new("version.command.print-package-and-spec-version", "version.version_command_should_print_package_and_spec_version", &["#treeboot-version"]), ported::version::version_command_should_print_package_and_spec_version),
    CaseDefinition::new(CaseMetadata::new("version.command.support-json-yaml-and-text-formats", "version.version_command_should_support_json_yaml_and_text_formats", &["#treeboot-version"]), ported::version::version_command_should_support_json_yaml_and_text_formats),
    CaseDefinition::new(CaseMetadata::new("version.command-output-shortcuts.conflict-with-format", "version.version_command_output_shortcuts_should_conflict_with_format", &["#treeboot-version"]), ported::version::version_command_output_shortcuts_should_conflict_with_format),
    CaseDefinition::new(CaseMetadata::new("worktree.id-and-slug.print-bare-text-and-exact-structured-shapes", "worktree.worktree_id_and_slug_should_print_bare_text_and_exact_structured_shapes", &["#treeboot-worktree"]), ported::worktree::worktree_id_and_slug_should_print_bare_text_and_exact_structured_shapes),
    CaseDefinition::new(CaseMetadata::new("worktree.path-and-list.use-candidate-local-config-and-contract-order", "worktree.worktree_path_and_list_should_use_candidate_local_config_and_contract_order", &["#treeboot-worktree"]), ported::worktree::worktree_path_and_list_should_use_candidate_local_config_and_contract_order),
    CaseDefinition::new(CaseMetadata::new("worktree.list.keep-main-first-when-a-linked-path-sorts-before-it", "worktree.worktree_list_should_keep_main_first_when_a_linked_path_sorts_before_it", &["#treeboot-worktree"]), ported::worktree::worktree_list_should_keep_main_first_when_a_linked_path_sorts_before_it),
    CaseDefinition::new(CaseMetadata::new("worktree.commands.support-a-bare-primary-repository", "worktree.worktree_commands_should_support_a_bare_primary_repository", &["#treeboot-worktree"]), ported::worktree::worktree_commands_should_support_a_bare_primary_repository),
    CaseDefinition::new(CaseMetadata::new("worktree.path.emit-exact-structured-shapes", "worktree.worktree_path_should_emit_exact_structured_shapes", &["#treeboot-worktree"]), ported::worktree::worktree_path_should_emit_exact_structured_shapes),
    CaseDefinition::new(CaseMetadata::new("worktree.inspection.use-defaults-without-config", "worktree.worktree_inspection_should_use_defaults_without_config", &["#treeboot-worktree"]), ported::worktree::worktree_inspection_should_use_defaults_without_config),
    CaseDefinition::new(CaseMetadata::new("worktree.explicit-actual-worktree-identity.match-implicit-and-local-config", "worktree.explicit_actual_worktree_identity_should_match_implicit_and_local_config", &["#treeboot-worktree"]), ported::worktree::explicit_actual_worktree_identity_should_match_implicit_and_local_config),
    CaseDefinition::new(CaseMetadata::new("worktree.explicit-ordinary-directory-identity.work-outside-git-and-use-local-config", "worktree.explicit_ordinary_directory_identity_should_work_outside_git_and_use_local_config", &["#treeboot-worktree"]), ported::worktree::explicit_ordinary_directory_identity_should_work_outside_git_and_use_local_config),
    CaseDefinition::new(CaseMetadata::new("worktree.explicit-identity-relative-absolute-dot-and-dotdot.normalize-to-one-target", "worktree.explicit_identity_relative_absolute_dot_and_dotdot_should_normalize_to_one_target", &["#treeboot-worktree"]), ported::worktree::explicit_identity_relative_absolute_dot_and_dotdot_should_normalize_to_one_target),
    #[cfg(unix)]
    CaseDefinition::new(CaseMetadata::new("worktree.explicit-identity-symlink-alias.normalize-to-target", "worktree.explicit_identity_symlink_alias_should_normalize_to_target", &["#treeboot-worktree"]), ported::worktree::explicit_identity_symlink_alias_should_normalize_to_target),
    #[cfg(not(unix))]
    CaseDefinition::skipped(CaseMetadata::new("worktree.explicit-identity-symlink-alias.normalize-to-target", "worktree.explicit_identity_symlink_alias_should_normalize_to_target", &["#treeboot-worktree"]), "requires a Unix host"),
    CaseDefinition::new(CaseMetadata::new("worktree.explicit-nonexistent-identity.survive-ordinary-directory-creation", "worktree.explicit_nonexistent_identity_should_survive_ordinary_directory_creation", &["#treeboot-worktree"]), ported::worktree::explicit_nonexistent_identity_should_survive_ordinary_directory_creation),
    CaseDefinition::new(CaseMetadata::new("worktree.explicit-nonexistent-git-targets.keep-fallback-slug-after-creation", "worktree.explicit_nonexistent_git_targets_should_keep_fallback_slug_after_creation", &["#treeboot-worktree"]), ported::worktree::explicit_nonexistent_git_targets_should_keep_fallback_slug_after_creation),
    CaseDefinition::new(CaseMetadata::new("worktree.explicit-git-subdirectory.keep-exact-identity-and-config-scope", "worktree.explicit_git_subdirectory_should_keep_exact_identity_and_config_scope", &["#treeboot-worktree"]), ported::worktree::explicit_git_subdirectory_should_keep_exact_identity_and_config_scope),
    CaseDefinition::new(CaseMetadata::new("worktree.explicit-regular-file-and-invalid-config.fail-before-stdout", "worktree.explicit_regular_file_and_invalid_config_should_fail_before_stdout", &["#treeboot-worktree"]), ported::worktree::explicit_regular_file_and_invalid_config_should_fail_before_stdout),
    #[cfg(unix)]
    CaseDefinition::new(CaseMetadata::new("worktree.explicit-dangling-symlink.fail-before-stdout", "worktree.explicit_dangling_symlink_should_fail_before_stdout", &["#treeboot-worktree"]), ported::worktree::explicit_dangling_symlink_should_fail_before_stdout),
    #[cfg(not(unix))]
    CaseDefinition::skipped(CaseMetadata::new("worktree.explicit-dangling-symlink.fail-before-stdout", "worktree.explicit_dangling_symlink_should_fail_before_stdout", &["#treeboot-worktree"]), "requires a Unix host"),
    CaseDefinition::new(CaseMetadata::new("worktree.explicit-empty-path.be-a-usage-error-without-stdout", "worktree.explicit_empty_path_should_be_a_usage_error_without_stdout", &["#treeboot-worktree"]), ported::worktree::explicit_empty_path_should_be_a_usage_error_without_stdout),
    #[cfg(windows)]
    CaseDefinition::new(CaseMetadata::new("worktree.explicit-windows-special-relative-paths.fail-before-stdout", "worktree.explicit_windows_special_relative_paths_should_fail_before_stdout", &["#treeboot-worktree"]), ported::worktree::explicit_windows_special_relative_paths_should_fail_before_stdout),
    #[cfg(not(windows))]
    CaseDefinition::skipped(CaseMetadata::new("worktree.explicit-windows-special-relative-paths.fail-before-stdout", "worktree.explicit_windows_special_relative_paths_should_fail_before_stdout", &["#treeboot-worktree"]), "requires a Windows host"),
    #[cfg(target_os = "linux")]
    CaseDefinition::new(CaseMetadata::new("worktree.explicit-identity-path-parser.preserve-native-non-utf8-input", "worktree.explicit_identity_path_parser_should_preserve_native_non_utf8_input", &["#treeboot-worktree"]), ported::worktree::explicit_identity_path_parser_should_preserve_native_non_utf8_input),
    #[cfg(not(target_os = "linux"))]
    CaseDefinition::skipped(CaseMetadata::new("worktree.explicit-identity-path-parser.preserve-native-non-utf8-input", "worktree.explicit_identity_path_parser_should_preserve_native_non_utf8_input", &["#treeboot-worktree"]), "requires Linux because the case uses non-UTF-8 Git worktree paths"),
    CaseDefinition::new(CaseMetadata::new("worktree.explicit-identity.ignore-ambient-discovery-overrides", "worktree.explicit_identity_should_ignore_ambient_discovery_overrides", &["#treeboot-worktree"]), ported::worktree::explicit_identity_should_ignore_ambient_discovery_overrides),
    CaseDefinition::new(CaseMetadata::new("worktree.list.skip-stale-registered-paths", "worktree.worktree_list_should_skip_stale_registered_paths", &["#treeboot-worktree"]), ported::worktree::worktree_list_should_skip_stale_registered_paths),
    #[cfg(target_os = "linux")]
    CaseDefinition::new(CaseMetadata::new("worktree.text-paths.preserve-native-bytes-and-structured-fail-atomically", "worktree.worktree_text_paths_should_preserve_native_bytes_and_structured_fail_atomically", &["#treeboot-worktree"]), ported::worktree::worktree_text_paths_should_preserve_native_bytes_and_structured_fail_atomically),
    #[cfg(not(target_os = "linux"))]
    CaseDefinition::skipped(CaseMetadata::new("worktree.text-paths.preserve-native-bytes-and-structured-fail-atomically", "worktree.worktree_text_paths_should_preserve_native_bytes_and_structured_fail_atomically", &["#treeboot-worktree"]), "requires Linux because the case uses non-UTF-8 Git worktree paths"),
    CaseDefinition::new(CaseMetadata::new("worktree.path.report-missing-and-ambiguous-ids-without-stdout", "worktree.worktree_path_should_report_missing_and_ambiguous_ids_without_stdout", &["#treeboot-worktree"]), ported::worktree::worktree_path_should_report_missing_and_ambiguous_ids_without_stdout),
    CaseDefinition::new(CaseMetadata::new("worktree.malformed-sibling-config.fail-atomically-with-candidate-path", "worktree.malformed_sibling_config_should_fail_atomically_with_candidate_path", &["#treeboot-worktree"]), ported::worktree::malformed_sibling_config_should_fail_atomically_with_candidate_path),
    CaseDefinition::new(CaseMetadata::new("worktree.commands.fail-outside-git", "worktree.worktree_commands_should_fail_outside_git", &["#treeboot-worktree"]), ported::worktree::worktree_commands_should_fail_outside_git),
    CaseDefinition::new(CaseMetadata::new("worktree.commands.honor-recognized-ambient-environment", "worktree.worktree_commands_should_honor_recognized_ambient_environment", &["#treeboot-worktree"]), ported::worktree::worktree_commands_should_honor_recognized_ambient_environment),
    CaseDefinition::new(CaseMetadata::new("worktree.nested-help-and-version.be-exposed", "worktree.worktree_nested_help_and_version_should_be_exposed", &["#treeboot-worktree"]), ported::worktree::worktree_nested_help_and_version_should_be_exposed),
];
